In [2]:
import pandas as pd
import numpy as np

In [67]:
df=pd.read_csv("car_price_prediction.csv")

In [68]:
df.head(6)

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4
5,45802912,39493,891,HYUNDAI,Santa FE,2016,Jeep,Yes,Diesel,2,160931 km,4.0,Automatic,Front,04-May,Left wheel,White,4

In [69]:
df.shape

(19237, 18)

In [70]:
df["Levy"].replace("-",np.nan,inplace=True)
df["Levy"].isna().sum()

5819

In [71]:
df["Engine volume"].replace("0",np.nan,inplace=True)
df["Engine volume"].isna().sum()

10

In [72]:
df.dropna()

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4
5,45802912,39493,891,HYUNDAI,Santa FE,2016,Jeep,Yes,Diesel,2,160931 km,4.0,Automatic,Front,04-May,Left wheel,White,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19231,45772306,5802,1055,MERCEDES-BENZ,E 350,2013,Sedan,Yes,Diesel,3.5,107800 km,6.0,Automatic,Rear,04-May,Left wheel,Grey,12
19233,45778856,15681,831,HYUNDAI,Sonata,2011,Sedan,Yes,Petrol,2.4,161600 km,4.0,Tiptronic,Front,04-May,Left wheel,Red,8
19234,45804997,26108,836,HYUNDAI,Tucson,2010,Jeep,Yes,Diesel,2,116365 km,4.0,Automatic,Front,04-May,Left wheel,Grey,4
19235,45793526,5331,1288,CHEVROLET,Captiva,2007,Jeep,Yes,Diesel,2,51258 km,4.0,Automatic,Front,04-May,Left wheel,Black,4
19236,45813273,470,753,HYUNDAI,Sonata,2012,Sedan,Yes,Hybrid,2.4,186923 km,4.0,Automatic,Front,04-May,Left wheel,White,12

In [73]:
manufacturer_to_country = {
    "HYUNDAI": "South Korea",
    "TOYOTA": "Japan",
    "MERCEDES-BENZ": "Germany",
    "CHEVROLET": "United States",
    "LEXUS": "Japan",
    "FORD": "United States",
    "HONDA": "Japan",
    "BMW": "Germany",
    "SSANGYONG": "South Korea",
    "KIA": "South Korea",
    "NISSAN": "Japan",
    "VOLKSWAGEN": "Germany",
    "AUDI": "Germany",
    "SUBARU": "Japan",
    "MAZDA": "Japan",
    "JEEP": "United States",
    "DAEWOO": "South Korea",
    "OPEL": "Germany",
    "MITSUBISHI": "Japan",
    "DODGE": "United States",
    "FIAT": "Italy",
    "JAGUAR": "United Kingdom",
    "PORSCHE": "Germany",
    "MINI": "United Kingdom",
    "SUZUKI": "Japan",
    "LAND ROVER": "United Kingdom",
    "CHRYSLER": "United States",
    "BUICK": "United States",
    "GMC": "United States",
    "ACURA": "Japan",
    "RENAULT": "France",
    "CADILLAC": "United States",
    "INFINITI": "Japan",
    "LINCOLN": "United States",
    "VOLVO": "Sweden",
    "CITROEN": "France",
    "MERCURY": "United States",
    "MASERATI": "Italy",
    "DAIHATSU": "Japan",
    "FERRARI": "Italy",
    "SCION": "Japan",
    "PEUGEOT": "France",
    "VAZ": "Russia",
    "SKODA": "Czech Republic",
    "LAMBORGHINI": "Italy",
    "BENTLEY": "United Kingdom",
    "GAZ": "Russia",
    "TESLA": "United States",
    "HUMMER": "United States"
}

In [74]:
# Adding the 'Country' column to the DataFrame
df['Country'] = df['Manufacturer'].map(manufacturer_to_country)

print(df)

             ID  Price  Levy   Manufacturer    Model  Prod. year   Category  \
0      45654403  13328  1399          LEXUS   RX 450        2010       Jeep
1      44731507  16621  1018      CHEVROLET  Equinox        2011       Jeep
2      45774419   8467   NaN          HONDA      FIT        2006  Hatchback
3      45769185   3607   862           FORD   Escape        2011       Jeep
4      45809263  11726   446          HONDA      FIT        2014  Hatchback
...         ...    ...   ...            ...      ...         ...        ...
19232  45798355   8467   NaN  MERCEDES-BENZ  CLK 200        1999      Coupe
19233  45778856  15681   831        HYUNDAI   Sonata        2011      Sedan
19234  45804997  26108   836        HYUNDAI   Tucson        2010       Jeep
19235  45793526   5331  1288      CHEVROLET  Captiva        2007       Jeep
19236  45813273    470   753        HYUNDAI   Sonata        2012      Sedan

      Leather interior Fuel type Engine volume    Mileage  Cylinders  \
0                  Yes    Hybrid           3.5  186005 km        6.0
1                   No    Petrol             3  192000 km        6.0
2                   No    Petrol           1.3  200000 km        4.0
3                  Yes    Hybrid           2.5  168966 km        4.0
4                  Yes    Petrol           1.3   91901 km        4.0
...                ...       ...           ...        ...        ...
19232              Yes       CNG     2.0 Turbo  300000 km        4.0
19233              Yes    Petrol           2.4  161600 km        4.0
19234              Yes    Diesel             2  116365 km        4.0
19235              Yes    Diesel             2   51258 km        4.0
19236              Yes    Hybrid           2.4  186923 km        4.0

      Gear box type Drive wheels   Doors             Wheel   Color  Airbags  \
0         Automatic          4x4  04-May        Left wheel  Silver       12
1         Tiptronic          4x4  04-May        Left wheel   Black        8
2          Variator        Front  04-May  Right-hand drive   Black        2
3         Automatic          4x4  04-May        Left wheel   White        0
4         Automatic        Front  04-May        Left wheel  Silver        4
...             ...          ...     ...               ...     ...      ...
19232        Manual         Rear  02-Mar        Left wheel  Silver        5
19233     Tiptronic        Front  04-May        Left wheel     Red        8
19234     Automatic        Front  04-May        Left wheel    Grey        4
19235     Automatic        Front  04-May        Left wheel   Black        4
19236     Automatic        Front  04-May        Left wheel   White       12

             Country
0              Japan
1      United States
2              Japan
3      United States
4              Japan
...              ...
19232        Germany
19233    South Korea
19234    South Korea
19235  United States
19236    South Korea

[19237 rows x 19 columns]

In [75]:
df.head(10)

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags,Country
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12,Japan
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8,United States
2,45774419,8467,NaN,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2,Japan
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0,United States
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4,Japan
5,45802912,39493,891,HYUNDAI,Santa FE,2016,Jeep,Yes,Diesel,2,160931 km,4.0,Automatic,Front,04-May,Left wheel,White,4,South Korea
6,45656768,1803,761,TOYOTA,Prius,2010,Hatchback,Yes,Hybrid,1.8,258909 km,4.0,Automatic,Front,04-May,Left wheel,White,12,Japan
7,45816158,549,751,HYUNDAI,Sonata,2013,Sedan,Yes,Petrol,2.4,216118 km,4.0,Automatic,Front,04-May,Left wheel,Grey,12,South Korea
8,45641395,1098,394,TOYOTA,Camry,2014,Sedan,Yes,Hybrid,2.5,398069 km,4.0,Automatic,Front,04-May,Left wheel,Black,12,Japan
9,45756839,26657,NaN,LEXUS,RX 350,2007,Jeep,Yes,Petrol,3.5,128500 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12,Japan

In [76]:
df=df.dropna()

In [77]:
df.head(10)

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags,Country
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12,Japan
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8,United States
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0,United States
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4,Japan
5,45802912,39493,891,HYUNDAI,Santa FE,2016,Jeep,Yes,Diesel,2,160931 km,4.0,Automatic,Front,04-May,Left wheel,White,4,South Korea
6,45656768,1803,761,TOYOTA,Prius,2010,Hatchback,Yes,Hybrid,1.8,258909 km,4.0,Automatic,Front,04-May,Left wheel,White,12,Japan
7,45816158,549,751,HYUNDAI,Sonata,2013,Sedan,Yes,Petrol,2.4,216118 km,4.0,Automatic,Front,04-May,Left wheel,Grey,12,South Korea
8,45641395,1098,394,TOYOTA,Camry,2014,Sedan,Yes,Hybrid,2.5,398069 km,4.0,Automatic,Front,04-May,Left wheel,Black,12,Japan
10,45621750,941,1053,MERCEDES-BENZ,E 350,2014,Sedan,Yes,Diesel,3.5,184467 km,6.0,Automatic,Rear,04-May,Left wheel,White,12,Germany
13,45661288,1019,1055,LEXUS,RX 450,2013,Jeep,Yes,Hybrid,3.5,138038 km,6.0,Automatic,Front,04-May,Left wheel,White,12,Japan

In [78]:
df['Mileage'] = df['Mileage'].str.replace('km', '').astype(int)
df['Engine volume'] = df['Engine volume'].str.replace('Turbo', '').astype(float)

In [79]:
df['Condition'] = np.where(df['Mileage'] == 0, 'Brand_New', 'Used')

In [80]:
df.head(10)

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags,Country,Condition
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005,6.0,Automatic,4x4,04-May,Left wheel,Silver,12,Japan,Used
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3.0,192000,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8,United States,Used
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966,4.0,Automatic,4x4,04-May,Left wheel,White,0,United States,Used
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901,4.0,Automatic,Front,04-May,Left wheel,Silver,4,Japan,Used
5,45802912,39493,891,HYUNDAI,Santa FE,2016,Jeep,Yes,Diesel,2.0,160931,4.0,Automatic,Front,04-May,Left wheel,White,4,South Korea,Used
6,45656768,1803,761,TOYOTA,Prius,2010,Hatchback,Yes,Hybrid,1.8,258909,4.0,Automatic,Front,04-May,Left wheel,White,12,Japan,Used
7,45816158,549,751,HYUNDAI,Sonata,2013,Sedan,Yes,Petrol,2.4,216118,4.0,Automatic,Front,04-May,Left wheel,Grey,12,South Korea,Used
8,45641395,1098,394,TOYOTA,Camry,2014,Sedan,Yes,Hybrid,2.5,398069,4.0,Automatic,Front,04-May,Left wheel,Black,12,Japan,Used
10,45621750,941,1053,MERCEDES-BENZ,E 350,2014,Sedan,Yes,Diesel,3.5,184467,6.0,Automatic,Rear,04-May,Left wheel,White,12,Germany,Used
13,45661288,1019,1055,LEXUS,RX 450,2013,Jeep,Yes,Hybrid,3.5,138038,6.0,Automatic,Front,04-May,Left wheel,White,12,Japan,Used

Replace the 4-may and 2-may to 4-5 and 2-3

In [83]:
df["Doors"].replace("04-May","4-5",inplace=True)
df["Doors"].replace("02-May","2-3",inplace=True)

In [84]:
df.head(10)

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags,Country,Condition
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005,6.0,Automatic,4x4,4-5,Left wheel,Silver,12,Japan,Used
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3.0,192000,6.0,Tiptronic,4x4,4-5,Left wheel,Black,8,United States,Used
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966,4.0,Automatic,4x4,4-5,Left wheel,White,0,United States,Used
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901,4.0,Automatic,Front,4-5,Left wheel,Silver,4,Japan,Used
5,45802912,39493,891,HYUNDAI,Santa FE,2016,Jeep,Yes,Diesel,2.0,160931,4.0,Automatic,Front,4-5,Left wheel,White,4,South Korea,Used
6,45656768,1803,761,TOYOTA,Prius,2010,Hatchback,Yes,Hybrid,1.8,258909,4.0,Automatic,Front,4-5,Left wheel,White,12,Japan,Used
7,45816158,549,751,HYUNDAI,Sonata,2013,Sedan,Yes,Petrol,2.4,216118,4.0,Automatic,Front,4-5,Left wheel,Grey,12,South Korea,Used
8,45641395,1098,394,TOYOTA,Camry,2014,Sedan,Yes,Hybrid,2.5,398069,4.0,Automatic,Front,4-5,Left wheel,Black,12,Japan,Used
10,45621750,941,1053,MERCEDES-BENZ,E 350,2014,Sedan,Yes,Diesel,3.5,184467,6.0,Automatic,Rear,4-5,Left wheel,White,12,Germany,Used
13,45661288,1019,1055,LEXUS,RX 450,2013,Jeep,Yes,Hybrid,3.5,138038,6.0,Automatic,Front,4-5,Left wheel,White,12,Japan,Used

In [87]:
df.to_csv('new_carprices.csv', index=False)